GET http://localhost:8000/

###

POST http://localhost:8000/tokenGeneration

###

POST http://localhost:8000/tokenVerification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJvY3RiYXRjaCIsImVtYWlsIjoib2N0QGdtYWlsLmNvbSIsImlhdCI6MTY1NDQxNDI1M30.eHCwekebAwcGvy0YfaRPLUhK88WBM8dQ2as7ekafl4I
